# Generated by Django 2.2 on 2019-05-01 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(blank=True, max_length=20, verbose_name='快递编号')),
                ('ename', models.CharField(db_index=True, max_length=10, verbose_name='快递名称')),
                ('etype', models.CharField(default='other', max_length=20, verbose_name='快递100对应的类型')),
                ('esort', models.SmallIntegerField(blank=True, default=9, verbose_name='快递排序')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('datastatus', models.SmallIntegerField(default=1, help_text='默认为1，99代表数据被删除', verbose_name='数据状态')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(help_text='同一文件MD5相同', max_length=32, verbose_name='文件MD5')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('datastatus', models.SmallIntegerField(default=1, help_text='默认为1，99代表数据被删除', verbose_name='数据状态')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='该编号是系统自动生成', verbose_name='订单编号')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('datastatus', models.SmallIntegerField(default=1, help_text='默认为1，99代表数据被删除', verbose_name='数据状态')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_num', models.CharField(db_index=True, help_text='您的物流信息', max_length=40, verbose_name='物流编号')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('datastatus', models.SmallIntegerField(default=1, help_text='默认为1，99代表数据被删除', verbose_name='数据状态')),
                ('express', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Express')),
            ],
        ),
    ]
