# Generated by Django 2.2 on 2019-05-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='express',
            options={'verbose_name': '快递公司', 'verbose_name_plural': '快递公司'},
        ),
        migrations.AlterModelOptions(
            name='expressorder',
            options={'verbose_name': '物流信息', 'verbose_name_plural': '物流信息'},
        ),
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': '文件信息', 'verbose_name_plural': '文件信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '买家订单', 'verbose_name_plural': '买家订单'},
        ),
    ]
