"""
Django settings for mysql_demo project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/zh-hans/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/zh-hans/2.2/ref/settings
"""

import os

# Base_dir：当前项目的绝对路径
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/zh-hans/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o96t+^%_!-@qlgo*0qqr%)2gca9s(l-!ihz_k252hol-ct_r#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "userapp",
]

# 中间件：https://docs.djangoproject.com/zh-hans/2.2/topics/http/middleware/
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysql_demo.urls'

# https://docs.djangoproject.com/zh-hans/2.2/ref/settings/#templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模版文件的绝对路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysql_demo.wsgi.application'

# Database
# https://docs.djangoproject.com/zh-hans/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',  # 使用哪个数据库
        'USER': 'root',  # mysql的用户名
        'PASSWORD': 'dntdnt',  # 用户名对应的密码
        'HOST': '127.0.0.1',  # 数据库服务的ip地址
        'PORT': 3306,  # 对应的端口
        # https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-OPTIONS
        'OPTIONS': {
            # https://docs.djangoproject.com/en/2.2/ref/settings/#autocommit
            # 'AUTOCOMMIT': False,
            # https://docs.djangoproject.com/zh-hans/2.2/ref/databases/#setting-sql-mode
            # SQLMode可以看我之前写的文章：https://www.cnblogs.com/dotnetcrazy/p/10374091.html
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 设置SQL_Model
        },
    }
}

# Password validation
# https://docs.djangoproject.com/zh-hans/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/zh-hans/2.2/topics/i18n/

# 使用中文（zh-hans可以这么记==>zh-汉'字'）
LANGUAGE_CODE = 'zh-hans'

# 设置中国时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/zh-hans/2.2/howto/static-files/

STATIC_URL = '/static/'
