# Generated by Django 2.1.5 on 2019-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
