# Generated by Django 2.1.5 on 2019-04-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190425_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfos',
            new_name='UserInfo',
        ),
    ]
