# Generated by Django 2.1.5 on 2019-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190425_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dataStatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(default=1556171125.8209407),
        ),
    ]
