# Generated by Django 2.1.5 on 2019-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190425_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='dataStatus',
            new_name='datastatus',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(default=1556171175.1334999),
        ),
    ]
